# Generated by Django 4.0.3 on 2022-04-06 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_cart_user_alter_commentsproducts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsproducts',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.abstractproduct'),
        ),
    ]
